language: node_js
node_js:
  - "lts/*"
install: npm install
cache:
  directories:
    - node_modules
script:
  - npm test
before_install: npm install -g greenkeeper-lockfile@1
before_script: greenkeeper-lockfile-update
after_script: greenkeeper-lockfile-upload
